################################################################################
### WARNING Core Configuration Settings: confirm before adoption ###############
esp32:
  board: esp32dev
  framework:
    type: esp-idf
### Core Template 2.1
packages:
################################################################################
### Custom packagages NON TEMPLATE
### 
### Control Components ###################
###
###  # Humidor Set Points: HA configurable
  climate_target: !include humidor-build/climate-setpoint.yaml
  # Exposes target humidity set point and sends to PID
###  # Humidor Climate Output: PWM Fan using LEDC
  climate_output: !include humidor-build/climate-output.yaml
  # Exposes output and RPM has option for manual over-ride
###  # Humidor Climate Sensors: DHT22
  climate_sensors: !include humidor-build/climate-sensors.yaml
  # Exposes humidity and temp
###
  # PID Controller & Tuning ###################
  PID_controller: !include humidor-build/PID_controller.yaml
  # PID function to control climate. Exposes algorithm terms as sensors
  PID_tuning: !include humidor-build/PID_controller_tuning.yaml
  # Optional?!? (Seems to break the PID if not included) Comment/uncomment package to remove/include? 
  # Exposes algorithm terms as controls for tuning.
###
################################################################################
  template: !include
    file: common/core-template.yaml
    vars:
### WARNING Template Substitutions: adjust during setup ########################
      devicename: "esphome-humidor"       #used as mDNS name
      friendly_devicename: "ESP Humidor"  #used in ESP Manager & HA Device
      device_ip_address: "10.0.20.252"    #must be DHCP reserved. For wifi settings changes / mDNS failures
### Troubleshooting wifi: Remove commments to override template
#wifi:
#  use_address: ${devicename}.local
#  use_address: ${device_ip_address} #set in Template Substitutions above
###
substitutions: ### WARNING Naming Substituion: Adjust during setup ############################
  device_namelabel: "Humidor"
### END Core Template
################################################################################
###
### Device Specific Substitutions ##############################################
# Wiring Substitutions
# Pin_VCC #Red, Yellow Thin
# Pin_GND #Black x2
  Pin_DHT_sensor: "GPIO21" #Green
  Pin_Fan_PWMinput: "GPIO17" #Blue Thin
  Pin_Fan_RPMoutput: "GPIO16" #Green Thin
# Configuration Parameters
  humidity_setpoint_select_low: "65" #Lowest setpoint available in HA
  humidity_setpoint_select_high: "75" #Highest setpoint available in HA
###
### Custom Device Configuration ################################################
###
###  Control State #1 Running: PID Contoller ###################################
#

switch:
  - platform: template
    name: "${friendly_devicename}: Run"
    id: "${friendly_devicename}_runnig"
#    icon: 
    restore_mode: ALWAYS_ON
#    on_turn_on: set climate to heat
#       turn off pause
#       turn off stop

button:
  - platform: template
    name: "${friendly_devicename}: Run"
    id: "${friendly_devicename}_run"
    on_press:
      then:
        switch.turn_on: ${friendly_devicename}_runnig


#
###  Control State #2 Paused #######################################
#
#
#
###  Control State #3 Stopped ######################################
#
# Fan running without humidity rising?
# Humidity below a threshold? Will opening trigger a false alarm?
# Stop running fan at full speed until refilled?
